// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.9.0
// source: gaming.proto

package gaming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nickname  string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gamename  string `protobuf:"bytes,3,opt,name=gamename,proto3" json:"gamename,omitempty"`
	ClientDes string `protobuf:"bytes,4,opt,name=clientDes,proto3" json:"clientDes,omitempty"`
}

func (x *StartGameReq) Reset() {
	*x = StartGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameReq) ProtoMessage() {}

func (x *StartGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameReq.ProtoReflect.Descriptor instead.
func (*StartGameReq) Descriptor() ([]byte, []int) {
	return file_gaming_proto_rawDescGZIP(), []int{0}
}

func (x *StartGameReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StartGameReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *StartGameReq) GetGamename() string {
	if x != nil {
		return x.Gamename
	}
	return ""
}

func (x *StartGameReq) GetClientDes() string {
	if x != nil {
		return x.ClientDes
	}
	return ""
}

type StartGameRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode   int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Msg       string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ServerDes string `protobuf:"bytes,3,opt,name=serverDes,proto3" json:"serverDes,omitempty"`
}

func (x *StartGameRsp) Reset() {
	*x = StartGameRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gaming_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRsp) ProtoMessage() {}

func (x *StartGameRsp) ProtoReflect() protoreflect.Message {
	mi := &file_gaming_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRsp.ProtoReflect.Descriptor instead.
func (*StartGameRsp) Descriptor() ([]byte, []int) {
	return file_gaming_proto_rawDescGZIP(), []int{1}
}

func (x *StartGameRsp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *StartGameRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *StartGameRsp) GetServerDes() string {
	if x != nil {
		return x.ServerDes
	}
	return ""
}

var File_gaming_proto protoreflect.FileDescriptor

var file_gaming_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x22, 0x80, 0x01, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x73, 0x22, 0x58, 0x0a, 0x0c, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x44, 0x65, 0x73, 0x32, 0x4a, 0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x2e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gaming_proto_rawDescOnce sync.Once
	file_gaming_proto_rawDescData = file_gaming_proto_rawDesc
)

func file_gaming_proto_rawDescGZIP() []byte {
	file_gaming_proto_rawDescOnce.Do(func() {
		file_gaming_proto_rawDescData = protoimpl.X.CompressGZIP(file_gaming_proto_rawDescData)
	})
	return file_gaming_proto_rawDescData
}

var file_gaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gaming_proto_goTypes = []interface{}{
	(*StartGameReq)(nil), // 0: gaming.startGameReq
	(*StartGameRsp)(nil), // 1: gaming.startGameRsp
}
var file_gaming_proto_depIdxs = []int32{
	0, // 0: gaming.GamingService.StartGame:input_type -> gaming.startGameReq
	1, // 1: gaming.GamingService.StartGame:output_type -> gaming.startGameRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gaming_proto_init() }
func file_gaming_proto_init() {
	if File_gaming_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gaming_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gaming_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gaming_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gaming_proto_goTypes,
		DependencyIndexes: file_gaming_proto_depIdxs,
		MessageInfos:      file_gaming_proto_msgTypes,
	}.Build()
	File_gaming_proto = out.File
	file_gaming_proto_rawDesc = nil
	file_gaming_proto_goTypes = nil
	file_gaming_proto_depIdxs = nil
}
