// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.9.0
// source: naming.proto

package naming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	IP          string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Port        int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *RegisterServiceReq) Reset() {
	*x = RegisterServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_naming_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceReq) ProtoMessage() {}

func (x *RegisterServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceReq.ProtoReflect.Descriptor instead.
func (*RegisterServiceReq) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterServiceReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterServiceReq) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *RegisterServiceReq) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RegisterServiceRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *RegisterServiceRsp) Reset() {
	*x = RegisterServiceRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_naming_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterServiceRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRsp) ProtoMessage() {}

func (x *RegisterServiceRsp) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRsp.ProtoReflect.Descriptor instead.
func (*RegisterServiceRsp) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterServiceRsp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *RegisterServiceRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FindServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
}

func (x *FindServiceReq) Reset() {
	*x = FindServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_naming_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindServiceReq) ProtoMessage() {}

func (x *FindServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindServiceReq.ProtoReflect.Descriptor instead.
func (*FindServiceReq) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{2}
}

func (x *FindServiceReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type FindServiceRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode     int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Msg         string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ServiceName string `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	IP          string `protobuf:"bytes,4,opt,name=IP,proto3" json:"IP,omitempty"`
	Port        int32  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *FindServiceRsp) Reset() {
	*x = FindServiceRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_naming_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindServiceRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindServiceRsp) ProtoMessage() {}

func (x *FindServiceRsp) ProtoReflect() protoreflect.Message {
	mi := &file_naming_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindServiceRsp.ProtoReflect.Descriptor instead.
func (*FindServiceRsp) Descriptor() ([]byte, []int) {
	return file_naming_proto_rawDescGZIP(), []int{3}
}

func (x *FindServiceRsp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *FindServiceRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FindServiceRsp) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *FindServiceRsp) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *FindServiceRsp) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_naming_proto protoreflect.FileDescriptor

var file_naming_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x22, 0x5a, 0x0a, 0x12, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x22, 0x40, 0x0a, 0x12, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x32, 0x0a, 0x0e, 0x66, 0x69, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x0e, 0x66, 0x69, 0x6e,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x32, 0x9d, 0x01,
	0x0a, 0x0d, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4b, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x1a, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0b,
	0x46, 0x69, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x6e, 0x61,
	0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x66, 0x69, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x66, 0x69, 0x6e,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x3b, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_naming_proto_rawDescOnce sync.Once
	file_naming_proto_rawDescData = file_naming_proto_rawDesc
)

func file_naming_proto_rawDescGZIP() []byte {
	file_naming_proto_rawDescOnce.Do(func() {
		file_naming_proto_rawDescData = protoimpl.X.CompressGZIP(file_naming_proto_rawDescData)
	})
	return file_naming_proto_rawDescData
}

var file_naming_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_naming_proto_goTypes = []interface{}{
	(*RegisterServiceReq)(nil), // 0: naming.registerServiceReq
	(*RegisterServiceRsp)(nil), // 1: naming.registerServiceRsp
	(*FindServiceReq)(nil),     // 2: naming.findServiceReq
	(*FindServiceRsp)(nil),     // 3: naming.findServiceRsp
}
var file_naming_proto_depIdxs = []int32{
	0, // 0: naming.NamingService.RegisterService:input_type -> naming.registerServiceReq
	2, // 1: naming.NamingService.FindService:input_type -> naming.findServiceReq
	1, // 2: naming.NamingService.RegisterService:output_type -> naming.registerServiceRsp
	3, // 3: naming.NamingService.FindService:output_type -> naming.findServiceRsp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_naming_proto_init() }
func file_naming_proto_init() {
	if File_naming_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_naming_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_naming_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterServiceRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_naming_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_naming_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindServiceRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_naming_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_naming_proto_goTypes,
		DependencyIndexes: file_naming_proto_depIdxs,
		MessageInfos:      file_naming_proto_msgTypes,
	}.Build()
	File_naming_proto = out.File
	file_naming_proto_rawDesc = nil
	file_naming_proto_goTypes = nil
	file_naming_proto_depIdxs = nil
}
